// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockScheduleRepository creates a new instance of MockScheduleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScheduleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScheduleRepository {
	mock := &MockScheduleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockScheduleRepository is an autogenerated mock type for the ScheduleRepository type
type MockScheduleRepository struct {
	mock.Mock
}

type MockScheduleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScheduleRepository) EXPECT() *MockScheduleRepository_Expecter {
	return &MockScheduleRepository_Expecter{mock: &_m.Mock}
}

// ExistsByRoomID provides a mock function for the type MockScheduleRepository
func (_mock *MockScheduleRepository) ExistsByRoomID(ctx context.Context, roomID string) (bool, error) {
	ret := _mock.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByRoomID")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, roomID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, roomID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScheduleRepository_ExistsByRoomID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByRoomID'
type MockScheduleRepository_ExistsByRoomID_Call struct {
	*mock.Call
}

// ExistsByRoomID is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
func (_e *MockScheduleRepository_Expecter) ExistsByRoomID(ctx interface{}, roomID interface{}) *MockScheduleRepository_ExistsByRoomID_Call {
	return &MockScheduleRepository_ExistsByRoomID_Call{Call: _e.mock.On("ExistsByRoomID", ctx, roomID)}
}

func (_c *MockScheduleRepository_ExistsByRoomID_Call) Run(run func(ctx context.Context, roomID string)) *MockScheduleRepository_ExistsByRoomID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockScheduleRepository_ExistsByRoomID_Call) Return(b bool, err error) *MockScheduleRepository_ExistsByRoomID_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockScheduleRepository_ExistsByRoomID_Call) RunAndReturn(run func(ctx context.Context, roomID string) (bool, error)) *MockScheduleRepository_ExistsByRoomID_Call {
	_c.Call.Return(run)
	return _c
}
