services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-meeting_booking}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-meeting_booking}"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrator:
    image: migrate/migrate:v4.17.0
    profiles:
      - migrations
    volumes:
      - ./migrations:/migrations
    entrypoint: [
      "migrate",
      "-path",
      "./migrations",
      "-database",
      "postgres://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-pass}@postgres:5432/${POSTGRES_DB:-meeting_booking}?sslmode=disable"
    ]
    command: ["up"]
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  app:
    build: .
    ports:
      - "${HTTP_PORT:-8080}:${HTTP_PORT:-8080}"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      HTTP_PORT: ${HTTP_PORT:-8080}

      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
      POSTGRES_DB: ${POSTGRES_DB:-meeting_booking}
      POSTGRES_SSLMODE: disable

      JWT_SIGN_KEY: ${JWT_SIGN_KEY:-secret}

      PASSWORD_HASHER_SALT: ${PASSWORD_HASHER_SALT:-}
    volumes:
      - ./config:/app/config:ro
    restart: unless-stopped

volumes:
  postgres_data: