// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenManager creates a new instance of MockTokenManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenManager {
	mock := &MockTokenManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenManager is an autogenerated mock type for the TokenManager type
type MockTokenManager struct {
	mock.Mock
}

type MockTokenManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenManager) EXPECT() *MockTokenManager_Expecter {
	return &MockTokenManager_Expecter{mock: &_m.Mock}
}

// CreateToken provides a mock function for the type MockTokenManager
func (_mock *MockTokenManager) CreateToken(userID string, role string, accessTTL time.Duration) (string, error) {
	ret := _mock.Called(userID, role, accessTTL)

	if len(ret) == 0 {
		panic("no return value specified for CreateToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, time.Duration) (string, error)); ok {
		return returnFunc(userID, role, accessTTL)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, time.Duration) string); ok {
		r0 = returnFunc(userID, role, accessTTL)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, time.Duration) error); ok {
		r1 = returnFunc(userID, role, accessTTL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenManager_CreateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateToken'
type MockTokenManager_CreateToken_Call struct {
	*mock.Call
}

// CreateToken is a helper method to define mock.On call
//   - userID string
//   - role string
//   - accessTTL time.Duration
func (_e *MockTokenManager_Expecter) CreateToken(userID interface{}, role interface{}, accessTTL interface{}) *MockTokenManager_CreateToken_Call {
	return &MockTokenManager_CreateToken_Call{Call: _e.mock.On("CreateToken", userID, role, accessTTL)}
}

func (_c *MockTokenManager_CreateToken_Call) Run(run func(userID string, role string, accessTTL time.Duration)) *MockTokenManager_CreateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTokenManager_CreateToken_Call) Return(s string, err error) *MockTokenManager_CreateToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenManager_CreateToken_Call) RunAndReturn(run func(userID string, role string, accessTTL time.Duration) (string, error)) *MockTokenManager_CreateToken_Call {
	_c.Call.Return(run)
	return _c
}
