// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSlotRepository creates a new instance of MockSlotRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSlotRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSlotRepository {
	mock := &MockSlotRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSlotRepository is an autogenerated mock type for the SlotRepository type
type MockSlotRepository struct {
	mock.Mock
}

type MockSlotRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSlotRepository) EXPECT() *MockSlotRepository_Expecter {
	return &MockSlotRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockSlotRepository
func (_mock *MockSlotRepository) Create(ctx context.Context, roomID string, startAt time.Time, endAt time.Time) error {
	ret := _mock.Called(ctx, roomID, startAt, endAt)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) error); ok {
		r0 = returnFunc(ctx, roomID, startAt, endAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSlotRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSlotRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
//   - startAt time.Time
//   - endAt time.Time
func (_e *MockSlotRepository_Expecter) Create(ctx interface{}, roomID interface{}, startAt interface{}, endAt interface{}) *MockSlotRepository_Create_Call {
	return &MockSlotRepository_Create_Call{Call: _e.mock.On("Create", ctx, roomID, startAt, endAt)}
}

func (_c *MockSlotRepository_Create_Call) Run(run func(ctx context.Context, roomID string, startAt time.Time, endAt time.Time)) *MockSlotRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSlotRepository_Create_Call) Return(err error) *MockSlotRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSlotRepository_Create_Call) RunAndReturn(run func(ctx context.Context, roomID string, startAt time.Time, endAt time.Time) error) *MockSlotRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}
