// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/internships-backend/test-backend-the-new-day/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSlotLister creates a new instance of MockSlotLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSlotLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSlotLister {
	mock := &MockSlotLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSlotLister is an autogenerated mock type for the SlotLister type
type MockSlotLister struct {
	mock.Mock
}

type MockSlotLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSlotLister) EXPECT() *MockSlotLister_Expecter {
	return &MockSlotLister_Expecter{mock: &_m.Mock}
}

// ListAvailableSlots provides a mock function for the type MockSlotLister
func (_mock *MockSlotLister) ListAvailableSlots(ctx context.Context, roomID string, date time.Time) ([]*entity.Slot, error) {
	ret := _mock.Called(ctx, roomID, date)

	if len(ret) == 0 {
		panic("no return value specified for ListAvailableSlots")
	}

	var r0 []*entity.Slot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) ([]*entity.Slot, error)); ok {
		return returnFunc(ctx, roomID, date)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) []*entity.Slot); ok {
		r0 = returnFunc(ctx, roomID, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Slot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = returnFunc(ctx, roomID, date)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSlotLister_ListAvailableSlots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAvailableSlots'
type MockSlotLister_ListAvailableSlots_Call struct {
	*mock.Call
}

// ListAvailableSlots is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
//   - date time.Time
func (_e *MockSlotLister_Expecter) ListAvailableSlots(ctx interface{}, roomID interface{}, date interface{}) *MockSlotLister_ListAvailableSlots_Call {
	return &MockSlotLister_ListAvailableSlots_Call{Call: _e.mock.On("ListAvailableSlots", ctx, roomID, date)}
}

func (_c *MockSlotLister_ListAvailableSlots_Call) Run(run func(ctx context.Context, roomID string, date time.Time)) *MockSlotLister_ListAvailableSlots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSlotLister_ListAvailableSlots_Call) Return(slots []*entity.Slot, err error) *MockSlotLister_ListAvailableSlots_Call {
	_c.Call.Return(slots, err)
	return _c
}

func (_c *MockSlotLister_ListAvailableSlots_Call) RunAndReturn(run func(ctx context.Context, roomID string, date time.Time) ([]*entity.Slot, error)) *MockSlotLister_ListAvailableSlots_Call {
	_c.Call.Return(run)
	return _c
}
