// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/internships-backend/test-backend-the-new-day/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBookingLister creates a new instance of MockBookingLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingLister {
	mock := &MockBookingLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBookingLister is an autogenerated mock type for the BookingLister type
type MockBookingLister struct {
	mock.Mock
}

type MockBookingLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingLister) EXPECT() *MockBookingLister_Expecter {
	return &MockBookingLister_Expecter{mock: &_m.Mock}
}

// ListBookings provides a mock function for the type MockBookingLister
func (_mock *MockBookingLister) ListBookings(ctx context.Context, page int, pageSize int) ([]*entity.Booking, int, error) {
	ret := _mock.Called(ctx, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListBookings")
	}

	var r0 []*entity.Booking
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*entity.Booking, int, error)); ok {
		return returnFunc(ctx, page, pageSize)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*entity.Booking); ok {
		r0 = returnFunc(ctx, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = returnFunc(ctx, page, pageSize)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = returnFunc(ctx, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockBookingLister_ListBookings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBookings'
type MockBookingLister_ListBookings_Call struct {
	*mock.Call
}

// ListBookings is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - pageSize int
func (_e *MockBookingLister_Expecter) ListBookings(ctx interface{}, page interface{}, pageSize interface{}) *MockBookingLister_ListBookings_Call {
	return &MockBookingLister_ListBookings_Call{Call: _e.mock.On("ListBookings", ctx, page, pageSize)}
}

func (_c *MockBookingLister_ListBookings_Call) Run(run func(ctx context.Context, page int, pageSize int)) *MockBookingLister_ListBookings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBookingLister_ListBookings_Call) Return(bookings []*entity.Booking, n int, err error) *MockBookingLister_ListBookings_Call {
	_c.Call.Return(bookings, n, err)
	return _c
}

func (_c *MockBookingLister_ListBookings_Call) RunAndReturn(run func(ctx context.Context, page int, pageSize int) ([]*entity.Booking, int, error)) *MockBookingLister_ListBookings_Call {
	_c.Call.Return(run)
	return _c
}
