// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/internships-backend/test-backend-the-new-day/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBookingCreator creates a new instance of MockBookingCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingCreator {
	mock := &MockBookingCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBookingCreator is an autogenerated mock type for the BookingCreator type
type MockBookingCreator struct {
	mock.Mock
}

type MockBookingCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingCreator) EXPECT() *MockBookingCreator_Expecter {
	return &MockBookingCreator_Expecter{mock: &_m.Mock}
}

// CreateBooking provides a mock function for the type MockBookingCreator
func (_mock *MockBookingCreator) CreateBooking(ctx context.Context, slotID string, userID string, createConferenceLink bool) (*entity.Booking, error) {
	ret := _mock.Called(ctx, slotID, userID, createConferenceLink)

	if len(ret) == 0 {
		panic("no return value specified for CreateBooking")
	}

	var r0 *entity.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool) (*entity.Booking, error)); ok {
		return returnFunc(ctx, slotID, userID, createConferenceLink)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, bool) *entity.Booking); ok {
		r0 = returnFunc(ctx, slotID, userID, createConferenceLink)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = returnFunc(ctx, slotID, userID, createConferenceLink)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingCreator_CreateBooking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBooking'
type MockBookingCreator_CreateBooking_Call struct {
	*mock.Call
}

// CreateBooking is a helper method to define mock.On call
//   - ctx context.Context
//   - slotID string
//   - userID string
//   - createConferenceLink bool
func (_e *MockBookingCreator_Expecter) CreateBooking(ctx interface{}, slotID interface{}, userID interface{}, createConferenceLink interface{}) *MockBookingCreator_CreateBooking_Call {
	return &MockBookingCreator_CreateBooking_Call{Call: _e.mock.On("CreateBooking", ctx, slotID, userID, createConferenceLink)}
}

func (_c *MockBookingCreator_CreateBooking_Call) Run(run func(ctx context.Context, slotID string, userID string, createConferenceLink bool)) *MockBookingCreator_CreateBooking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBookingCreator_CreateBooking_Call) Return(booking *entity.Booking, err error) *MockBookingCreator_CreateBooking_Call {
	_c.Call.Return(booking, err)
	return _c
}

func (_c *MockBookingCreator_CreateBooking_Call) RunAndReturn(run func(ctx context.Context, slotID string, userID string, createConferenceLink bool) (*entity.Booking, error)) *MockBookingCreator_CreateBooking_Call {
	_c.Call.Return(run)
	return _c
}
