// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/internships-backend/test-backend-the-new-day/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBookingCanceler creates a new instance of MockBookingCanceler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingCanceler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingCanceler {
	mock := &MockBookingCanceler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBookingCanceler is an autogenerated mock type for the BookingCanceler type
type MockBookingCanceler struct {
	mock.Mock
}

type MockBookingCanceler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingCanceler) EXPECT() *MockBookingCanceler_Expecter {
	return &MockBookingCanceler_Expecter{mock: &_m.Mock}
}

// CancelBooking provides a mock function for the type MockBookingCanceler
func (_mock *MockBookingCanceler) CancelBooking(ctx context.Context, bookingID string, userID string) (*entity.Booking, error) {
	ret := _mock.Called(ctx, bookingID, userID)

	if len(ret) == 0 {
		panic("no return value specified for CancelBooking")
	}

	var r0 *entity.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*entity.Booking, error)); ok {
		return returnFunc(ctx, bookingID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *entity.Booking); ok {
		r0 = returnFunc(ctx, bookingID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, bookingID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingCanceler_CancelBooking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelBooking'
type MockBookingCanceler_CancelBooking_Call struct {
	*mock.Call
}

// CancelBooking is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingID string
//   - userID string
func (_e *MockBookingCanceler_Expecter) CancelBooking(ctx interface{}, bookingID interface{}, userID interface{}) *MockBookingCanceler_CancelBooking_Call {
	return &MockBookingCanceler_CancelBooking_Call{Call: _e.mock.On("CancelBooking", ctx, bookingID, userID)}
}

func (_c *MockBookingCanceler_CancelBooking_Call) Run(run func(ctx context.Context, bookingID string, userID string)) *MockBookingCanceler_CancelBooking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBookingCanceler_CancelBooking_Call) Return(booking *entity.Booking, err error) *MockBookingCanceler_CancelBooking_Call {
	_c.Call.Return(booking, err)
	return _c
}

func (_c *MockBookingCanceler_CancelBooking_Call) RunAndReturn(run func(ctx context.Context, bookingID string, userID string) (*entity.Booking, error)) *MockBookingCanceler_CancelBooking_Call {
	_c.Call.Return(run)
	return _c
}
