// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/internships-backend/test-backend-the-new-day/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMyBookingLister creates a new instance of MockMyBookingLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMyBookingLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMyBookingLister {
	mock := &MockMyBookingLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMyBookingLister is an autogenerated mock type for the MyBookingLister type
type MockMyBookingLister struct {
	mock.Mock
}

type MockMyBookingLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMyBookingLister) EXPECT() *MockMyBookingLister_Expecter {
	return &MockMyBookingLister_Expecter{mock: &_m.Mock}
}

// ListMyBookings provides a mock function for the type MockMyBookingLister
func (_mock *MockMyBookingLister) ListMyBookings(ctx context.Context, userID string) ([]*entity.Booking, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListMyBookings")
	}

	var r0 []*entity.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*entity.Booking, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*entity.Booking); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMyBookingLister_ListMyBookings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMyBookings'
type MockMyBookingLister_ListMyBookings_Call struct {
	*mock.Call
}

// ListMyBookings is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockMyBookingLister_Expecter) ListMyBookings(ctx interface{}, userID interface{}) *MockMyBookingLister_ListMyBookings_Call {
	return &MockMyBookingLister_ListMyBookings_Call{Call: _e.mock.On("ListMyBookings", ctx, userID)}
}

func (_c *MockMyBookingLister_ListMyBookings_Call) Run(run func(ctx context.Context, userID string)) *MockMyBookingLister_ListMyBookings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMyBookingLister_ListMyBookings_Call) Return(bookings []*entity.Booking, err error) *MockMyBookingLister_ListMyBookings_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *MockMyBookingLister_ListMyBookings_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*entity.Booking, error)) *MockMyBookingLister_ListMyBookings_Call {
	_c.Call.Return(run)
	return _c
}
