// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/internships-backend/test-backend-the-new-day/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockScheduleCreator creates a new instance of MockScheduleCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScheduleCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScheduleCreator {
	mock := &MockScheduleCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockScheduleCreator is an autogenerated mock type for the ScheduleCreator type
type MockScheduleCreator struct {
	mock.Mock
}

type MockScheduleCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScheduleCreator) EXPECT() *MockScheduleCreator_Expecter {
	return &MockScheduleCreator_Expecter{mock: &_m.Mock}
}

// CreateSchedule provides a mock function for the type MockScheduleCreator
func (_mock *MockScheduleCreator) CreateSchedule(ctx context.Context, roomID string, weekdays []int, startTime string, endTime string) (*entity.Schedule, error) {
	ret := _mock.Called(ctx, roomID, weekdays, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for CreateSchedule")
	}

	var r0 *entity.Schedule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []int, string, string) (*entity.Schedule, error)); ok {
		return returnFunc(ctx, roomID, weekdays, startTime, endTime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []int, string, string) *entity.Schedule); ok {
		r0 = returnFunc(ctx, roomID, weekdays, startTime, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Schedule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []int, string, string) error); ok {
		r1 = returnFunc(ctx, roomID, weekdays, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScheduleCreator_CreateSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSchedule'
type MockScheduleCreator_CreateSchedule_Call struct {
	*mock.Call
}

// CreateSchedule is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID string
//   - weekdays []int
//   - startTime string
//   - endTime string
func (_e *MockScheduleCreator_Expecter) CreateSchedule(ctx interface{}, roomID interface{}, weekdays interface{}, startTime interface{}, endTime interface{}) *MockScheduleCreator_CreateSchedule_Call {
	return &MockScheduleCreator_CreateSchedule_Call{Call: _e.mock.On("CreateSchedule", ctx, roomID, weekdays, startTime, endTime)}
}

func (_c *MockScheduleCreator_CreateSchedule_Call) Run(run func(ctx context.Context, roomID string, weekdays []int, startTime string, endTime string)) *MockScheduleCreator_CreateSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []int
		if args[2] != nil {
			arg2 = args[2].([]int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockScheduleCreator_CreateSchedule_Call) Return(schedule *entity.Schedule, err error) *MockScheduleCreator_CreateSchedule_Call {
	_c.Call.Return(schedule, err)
	return _c
}

func (_c *MockScheduleCreator_CreateSchedule_Call) RunAndReturn(run func(ctx context.Context, roomID string, weekdays []int, startTime string, endTime string) (*entity.Schedule, error)) *MockScheduleCreator_CreateSchedule_Call {
	_c.Call.Return(run)
	return _c
}
