// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/internships-backend/test-backend-the-new-day/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBookingRepository creates a new instance of MockBookingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingRepository {
	mock := &MockBookingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBookingRepository is an autogenerated mock type for the BookingRepository type
type MockBookingRepository struct {
	mock.Mock
}

type MockBookingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingRepository) EXPECT() *MockBookingRepository_Expecter {
	return &MockBookingRepository_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function for the type MockBookingRepository
func (_mock *MockBookingRepository) Cancel(ctx context.Context, bookingID string) (*entity.Booking, error) {
	ret := _mock.Called(ctx, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 *entity.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Booking, error)); ok {
		return returnFunc(ctx, bookingID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Booking); ok {
		r0 = returnFunc(ctx, bookingID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, bookingID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingRepository_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockBookingRepository_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingID string
func (_e *MockBookingRepository_Expecter) Cancel(ctx interface{}, bookingID interface{}) *MockBookingRepository_Cancel_Call {
	return &MockBookingRepository_Cancel_Call{Call: _e.mock.On("Cancel", ctx, bookingID)}
}

func (_c *MockBookingRepository_Cancel_Call) Run(run func(ctx context.Context, bookingID string)) *MockBookingRepository_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingRepository_Cancel_Call) Return(booking *entity.Booking, err error) *MockBookingRepository_Cancel_Call {
	_c.Call.Return(booking, err)
	return _c
}

func (_c *MockBookingRepository_Cancel_Call) RunAndReturn(run func(ctx context.Context, bookingID string) (*entity.Booking, error)) *MockBookingRepository_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockBookingRepository
func (_mock *MockBookingRepository) Create(ctx context.Context, slotID string, userID string, conferenceLink *string) (*entity.Booking, error) {
	ret := _mock.Called(ctx, slotID, userID, conferenceLink)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *string) (*entity.Booking, error)); ok {
		return returnFunc(ctx, slotID, userID, conferenceLink)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *string) *entity.Booking); ok {
		r0 = returnFunc(ctx, slotID, userID, conferenceLink)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *string) error); ok {
		r1 = returnFunc(ctx, slotID, userID, conferenceLink)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBookingRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - slotID string
//   - userID string
//   - conferenceLink *string
func (_e *MockBookingRepository_Expecter) Create(ctx interface{}, slotID interface{}, userID interface{}, conferenceLink interface{}) *MockBookingRepository_Create_Call {
	return &MockBookingRepository_Create_Call{Call: _e.mock.On("Create", ctx, slotID, userID, conferenceLink)}
}

func (_c *MockBookingRepository_Create_Call) Run(run func(ctx context.Context, slotID string, userID string, conferenceLink *string)) *MockBookingRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBookingRepository_Create_Call) Return(booking *entity.Booking, err error) *MockBookingRepository_Create_Call {
	_c.Call.Return(booking, err)
	return _c
}

func (_c *MockBookingRepository_Create_Call) RunAndReturn(run func(ctx context.Context, slotID string, userID string, conferenceLink *string) (*entity.Booking, error)) *MockBookingRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockBookingRepository
func (_mock *MockBookingRepository) FindByID(ctx context.Context, bookingID string) (*entity.Booking, error) {
	ret := _mock.Called(ctx, bookingID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Booking, error)); ok {
		return returnFunc(ctx, bookingID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Booking); ok {
		r0 = returnFunc(ctx, bookingID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, bookingID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockBookingRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingID string
func (_e *MockBookingRepository_Expecter) FindByID(ctx interface{}, bookingID interface{}) *MockBookingRepository_FindByID_Call {
	return &MockBookingRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, bookingID)}
}

func (_c *MockBookingRepository_FindByID_Call) Run(run func(ctx context.Context, bookingID string)) *MockBookingRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBookingRepository_FindByID_Call) Return(booking *entity.Booking, err error) *MockBookingRepository_FindByID_Call {
	_c.Call.Return(booking, err)
	return _c
}

func (_c *MockBookingRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, bookingID string) (*entity.Booking, error)) *MockBookingRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockBookingRepository
func (_mock *MockBookingRepository) List(ctx context.Context, offset int, limit int) ([]*entity.Booking, int, error) {
	ret := _mock.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entity.Booking
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*entity.Booking, int, error)); ok {
		return returnFunc(ctx, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*entity.Booking); ok {
		r0 = returnFunc(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = returnFunc(ctx, offset, limit)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = returnFunc(ctx, offset, limit)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockBookingRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockBookingRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int
//   - limit int
func (_e *MockBookingRepository_Expecter) List(ctx interface{}, offset interface{}, limit interface{}) *MockBookingRepository_List_Call {
	return &MockBookingRepository_List_Call{Call: _e.mock.On("List", ctx, offset, limit)}
}

func (_c *MockBookingRepository_List_Call) Run(run func(ctx context.Context, offset int, limit int)) *MockBookingRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBookingRepository_List_Call) Return(bookings []*entity.Booking, n int, err error) *MockBookingRepository_List_Call {
	_c.Call.Return(bookings, n, err)
	return _c
}

func (_c *MockBookingRepository_List_Call) RunAndReturn(run func(ctx context.Context, offset int, limit int) ([]*entity.Booking, int, error)) *MockBookingRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserFuture provides a mock function for the type MockBookingRepository
func (_mock *MockBookingRepository) ListByUserFuture(ctx context.Context, userID string, now time.Time) ([]*entity.Booking, error) {
	ret := _mock.Called(ctx, userID, now)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserFuture")
	}

	var r0 []*entity.Booking
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) ([]*entity.Booking, error)); ok {
		return returnFunc(ctx, userID, now)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) []*entity.Booking); ok {
		r0 = returnFunc(ctx, userID, now)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Booking)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = returnFunc(ctx, userID, now)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBookingRepository_ListByUserFuture_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserFuture'
type MockBookingRepository_ListByUserFuture_Call struct {
	*mock.Call
}

// ListByUserFuture is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - now time.Time
func (_e *MockBookingRepository_Expecter) ListByUserFuture(ctx interface{}, userID interface{}, now interface{}) *MockBookingRepository_ListByUserFuture_Call {
	return &MockBookingRepository_ListByUserFuture_Call{Call: _e.mock.On("ListByUserFuture", ctx, userID, now)}
}

func (_c *MockBookingRepository_ListByUserFuture_Call) Run(run func(ctx context.Context, userID string, now time.Time)) *MockBookingRepository_ListByUserFuture_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBookingRepository_ListByUserFuture_Call) Return(bookings []*entity.Booking, err error) *MockBookingRepository_ListByUserFuture_Call {
	_c.Call.Return(bookings, err)
	return _c
}

func (_c *MockBookingRepository_ListByUserFuture_Call) RunAndReturn(run func(ctx context.Context, userID string, now time.Time) ([]*entity.Booking, error)) *MockBookingRepository_ListByUserFuture_Call {
	_c.Call.Return(run)
	return _c
}
