// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/internships-backend/test-backend-the-new-day/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSlotRepository creates a new instance of MockSlotRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSlotRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSlotRepository {
	mock := &MockSlotRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSlotRepository is an autogenerated mock type for the SlotRepository type
type MockSlotRepository struct {
	mock.Mock
}

type MockSlotRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSlotRepository) EXPECT() *MockSlotRepository_Expecter {
	return &MockSlotRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockSlotRepository
func (_mock *MockSlotRepository) GetByID(ctx context.Context, slotID string) (*entity.Slot, error) {
	ret := _mock.Called(ctx, slotID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Slot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Slot, error)); ok {
		return returnFunc(ctx, slotID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Slot); ok {
		r0 = returnFunc(ctx, slotID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Slot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slotID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSlotRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockSlotRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - slotID string
func (_e *MockSlotRepository_Expecter) GetByID(ctx interface{}, slotID interface{}) *MockSlotRepository_GetByID_Call {
	return &MockSlotRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, slotID)}
}

func (_c *MockSlotRepository_GetByID_Call) Run(run func(ctx context.Context, slotID string)) *MockSlotRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSlotRepository_GetByID_Call) Return(slot *entity.Slot, err error) *MockSlotRepository_GetByID_Call {
	_c.Call.Return(slot, err)
	return _c
}

func (_c *MockSlotRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, slotID string) (*entity.Slot, error)) *MockSlotRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}
