// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/internships-backend/test-backend-the-new-day/internal/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRoomRepository creates a new instance of MockRoomRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoomRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoomRepository {
	mock := &MockRoomRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRoomRepository is an autogenerated mock type for the RoomRepository type
type MockRoomRepository struct {
	mock.Mock
}

type MockRoomRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoomRepository) EXPECT() *MockRoomRepository_Expecter {
	return &MockRoomRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRoomRepository
func (_mock *MockRoomRepository) Create(ctx context.Context, name string, description *string, capacity *int) (*entity.Room, error) {
	ret := _mock.Called(ctx, name, description, capacity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Room
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, *int) (*entity.Room, error)); ok {
		return returnFunc(ctx, name, description, capacity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string, *int) *entity.Room); ok {
		r0 = returnFunc(ctx, name, description, capacity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Room)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *string, *int) error); ok {
		r1 = returnFunc(ctx, name, description, capacity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoomRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRoomRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - description *string
//   - capacity *int
func (_e *MockRoomRepository_Expecter) Create(ctx interface{}, name interface{}, description interface{}, capacity interface{}) *MockRoomRepository_Create_Call {
	return &MockRoomRepository_Create_Call{Call: _e.mock.On("Create", ctx, name, description, capacity)}
}

func (_c *MockRoomRepository_Create_Call) Run(run func(ctx context.Context, name string, description *string, capacity *int)) *MockRoomRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 *int
		if args[3] != nil {
			arg3 = args[3].(*int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRoomRepository_Create_Call) Return(room *entity.Room, err error) *MockRoomRepository_Create_Call {
	_c.Call.Return(room, err)
	return _c
}

func (_c *MockRoomRepository_Create_Call) RunAndReturn(run func(ctx context.Context, name string, description *string, capacity *int) (*entity.Room, error)) *MockRoomRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRoomRepository
func (_mock *MockRoomRepository) List(ctx context.Context) ([]*entity.Room, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entity.Room
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*entity.Room, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*entity.Room); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Room)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoomRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRoomRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRoomRepository_Expecter) List(ctx interface{}) *MockRoomRepository_List_Call {
	return &MockRoomRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockRoomRepository_List_Call) Run(run func(ctx context.Context)) *MockRoomRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRoomRepository_List_Call) Return(rooms []*entity.Room, err error) *MockRoomRepository_List_Call {
	_c.Call.Return(rooms, err)
	return _c
}

func (_c *MockRoomRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]*entity.Room, error)) *MockRoomRepository_List_Call {
	_c.Call.Return(run)
	return _c
}
